FROM ubuntu:18.04

ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_FRONTEND noninteractive

ARG coq_version="8.8.2"

ENV COQBIN /usr/local/bin/
WORKDIR /tmp

# change apt source
RUN sed -i.bak -e "s%http://.*.ubuntu.com/ubuntu/%http://ftp.jaist.ac.jp/pub/Linux/ubuntu/%g" /etc/apt/sources.list
RUN apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates \
  camlp5 \
  liblablgtk-extras-ocaml-dev \
  liblablgtk2-ocaml-dev \
  ocaml \
  ocaml-findlib \
  vim \
  wget \
&& apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

RUN wget -O - "https://github.com/coq/coq/archive/V${coq_version}.tar.gz" | tar zxf - \
&& cd "coq-${coq_version}" \
&& ./configure -bindir  /usr/local/bin \
               -libdir /usr/local/lib/coq \
               -configdir /etc/xdg/coq \
               -datadir /usr/local/share/coq \
               -mandir /usr/local/share/man \
               -docdir /usr/local/share/doc/coq \
               -emacslib /usr/local/share/emacs/site-lisp \
               -coqdocdir /usr/local/share/texmf/tex/latex/misc \
&& make \
&& make install

WORKDIR /coq-work

CMD ["bash"]
