FROM ubuntu:18.04

ENV DEBCONF_NOWARNINGS yes
ENV DEBIAN_FRONTEND noninteractive

ARG coq_version="8.8.2"
ARG math_comp_version="1.7.0"

ENV COQBIN /usr/local/bin/
WORKDIR /tmp

# change apt source
RUN sed -i.bak -e "s%http://.*.ubuntu.com/ubuntu/%http://ftp.jaist.ac.jp/pub/Linux/ubuntu/%g" /etc/apt/sources.list
RUN apt-get update && apt-get install -y --no-install-recommends \
  camlp5 \
  liblablgtk-extras-ocaml-dev \
  liblablgtk2-ocaml-dev \
  ocaml \
  ocaml-findlib \
  vim \
  wget \
  x11-apps \
&& apt-get clean && rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*

RUN wget --no-check-certificate -O - "https://github.com/coq/coq/archive/V${coq_version}.tar.gz" | tar zxf - \
&& cd "coq-${coq_version}" \
&& ./configure -bindir  /usr/local/bin \
               -libdir /usr/local/lib/coq \
               -configdir /etc/xdg/coq \
               -datadir /usr/local/share/coq \
               -mandir /usr/local/share/man \
               -docdir /usr/local/share/doc/coq \
               -emacslib /usr/local/share/emacs/site-lisp \
               -coqdocdir /usr/local/share/texmf/tex/latex/misc \
&& make \
&& make install

RUN wget --no-check-certificate -O - "https://github.com/math-comp/math-comp/archive/mathcomp-${math_comp_version}.tar.gz" | tar zxf - \
&& cd "math-comp-mathcomp-${math_comp_version}/mathcomp" \
&& make \
&& make install

#COPY res/entrypoint.sh /usr/local/bin
#RUN chmod +x /usr/local/bin/entrypoint.sh

WORKDIR /coq-work

ENV COQ_USER developer
ENV COQ_UID 99999
ENV COQ_GID 99999

#ENTRYPOINT ["entrypoint.sh"]
CMD ["bash"]
